{% set version = "0.1.0" %}
{% set sha256 = "c9f280aede31cde748c635972101625b6287fb4558595d172308515f90b59978" %}

package:
  name: sklearn-contrib-py-earth
  version: {{ version }}

source:
  url: https://github.com/scikit-learn-contrib/py-earth/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-scikit-learn-0.22-compat.patch

build:
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv --install-option=--cythonize

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - python
    - pip
    - numpy
    # pyearth cimports BLAS from scipy
    - scipy >=0.18
    # add scikit-learn here to ensure we get a compatible scipy version
    - scikit-learn >=0.16,<0.20.0a0|>=0.22
    - six
  run:
    - python
    - six
    - {{ pin_compatible('scipy') }}
    # the patches add 0.22 compatibility but don't work with >=0.20,<0.22
    - scikit-learn >=0.16,<0.20.0a0|>=0.22

test:
  requires:
    - nose
    - pandas
    - statsmodels
    - patsy
    - sympy
  imports:
    - pyearth
  commands:
    - nosetests -s -v pyearth

about:
  home: https://github.com/scikit-learn-contrib/py-earth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: >
    A Python implementation of Jerome Friedman's
    Multivariate Adaptive Regression Splines
  description: >
    A Python implementation of Jerome Friedman's
    Multivariate Adaptive Regression Splines algorithm,
    in the style of scikit-learn.
  doc_url: http://contrib.scikit-learn.org/py-earth/
  dev_url: https://github.com/scikit-learn-contrib/py-earth

extra:
  recipe-maintainers:
    - mehdidc
    - rth
