{% set version = "0.1.0" %}
{% set sha256 = "c9f280aede31cde748c635972101625b6287fb4558595d172308515f90b59978" %}

package:
  name: sklearn-contrib-py-earth
  version: {{ version }}

source:
  url: https://github.com/scikit-learn-contrib/py-earth/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-scikit-learn-0.21-0.22-compat.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv --install-option=--cythonize

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    # Notes:
    # 1. Cython is not used in build as
    #     a) .c files are included
    #     b) with the current setup.py cythonizing requires an additional
    #        parameter
    # 2. pyearth cimports BLAS from scipy
    #    These combinations of pinned numpy/scipy versions
    #    are known to work, see related discussion in
    #    conda-forge/staged-recipes#4808 and conda-forge/implicit-feedstock#4
    - numpy
    - scipy >=0.18
    - six
  run:
    - python
    - six
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - scikit-learn >=0.16

test:
  requires:
    - nose
  imports:
    - pyearth
  commands:
    - nosetests -s -v pyearth

about:
  home: https://github.com/scikit-learn-contrib/py-earth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: >
    A Python implementation of Jerome Friedman's
    Multivariate Adaptive Regression Splines
  description: >
    A Python implementation of Jerome Friedman's
    Multivariate Adaptive Regression Splines algorithm,
    in the style of scikit-learn.
  doc_url: http://contrib.scikit-learn.org/py-earth/
  dev_url: https://github.com/scikit-learn-contrib/py-earth

extra:
  recipe-maintainers:
    - mehdidc
    - rth
