travis:
  secure:
    BINSTAR_TOKEN: yU7fifV/3xE2MSWS2oPPtBnUfBPx/cXAvP5uBSBJGm8t3TyZY3kxn0zxfObL0uMRcMWgsk03M9F/yUrVdFCJkhurtX4cmHlSH2lZE9HeEdD5Zv5l7Z20x3rU5H5cLGRbMJUoapJejGV1TB5XMPwEAZ1pRKbFum+xP32HB+cse/1UC+8fsc/+wcMsQr5wumd52Dspwv7FtVR9RmZ5mzI5AFdosLvcizYwvU7BDYciu+rJAKVI+gq/jfqeysK00uhvQvVjJanUHZ4QrtQIPaHUIJ2Ud/832gjNcKequ9k2dwiFGs+IqXzgYCFPU/2WN6TgYGD+B8LUm/MlGE1uLSidfdtew7YH4j6JNw50eefZlVqnuaA28yheF9Kw9py75BmJXnVeNs5gWKh/Zm4VBFW2c51BMFZDkdfUh+CGu2+2MMWKKktEpCh8LJplFRWtGi5vqnHbKcADeXKc5pgsFz2XtNvJZ0LmBfSV14HO7hJDffOK8JHTCw+5jEijt/jktDb0bpwTyH4VvwhzhdbCe8GQa53VoOL6bGg17RQrCW6Kin0ECiBsScdKmx311VaFtKynzOof6fsFXNRm97gm7nl4uMaXQn4HNyUjFmEQ6q9JufNNvESSuFv3t4WEBUBOrX4DWHePPs0gg5sPdY5TKd+kAucWwqpmvkK7Z7qubjgr82s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
