travis:
  secure:
    BINSTAR_TOKEN: axuf9hNLFW/8lInX7Taj1Cw+FchBGLsovxvHYKoTek64Q2ELlyAHsANEtFP4q1hv2lenMCPM+P0Vy6xZHvWuzkhKmNMGGolhqGlxGubklz9XdvEmDwoNvFl0pgaKDaLGxab93bzV9yWFZl68y2T1SmDUcam2TRbGaqKOPweROhByt8vQeriU+egZRe2l0JppaOc9Ve3I1rBuMmrHGIuF8DzhkuQZmKav2T2+YnBFzl7XrHD+WTa18YAZRWRhf9kEvYV013jJRsS+pryZR5WG8jjvVdIw+K8Z6VcSmCs6e2AbKKBLFWVlwa09Hdd6fNsgPted4SbhCUYfYqNBVNq+3X96QDzV4Pmuc/n4i8OGHorhHjBA/gNpJ+GKArka2SNfC5I/R+SS+pQ/QEuy3RmIhPEOHoQd+AH2+QDSAu26Opl1EXsnVOSxpUOVwC/2oonJVie7LkDdcYMDH3McUwsrOr8lKLtPjGXk6OMuU+FRWAuxY3b+7X4C8LW5AHSbwVeFmy4c0rFHWRZbyebgyk/oQ1NFv7USbrT1AGkbGsH/K5FBPV55r+yzklFQ8Dd29JKA/fIKAykWJNMcQMLNwtFDof+e38tGC1vIxYq3Nqs12Ls1NGH7JejwJLGB8RCvWtix4HPwbONWkYbEfEZ2mJlBcROJ9GuoGFLqCk9smGKY7NQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
