travis:
  secure:
    BINSTAR_TOKEN: du2XkF7Cf2nEtw25bd+07gXwEgn4DCWNFF+4aPbU2rkj7emrlQqe0HCtVL9hMqWCjC8TgOKGDHCBVxogeXukrGNCjI7R4mC5RHRJ4WLiDqe0lzQw739s/7qxieFoIl6WVz6tOvpGOsBVg6ljzt8jJZDxjuPDsqESvGOzVTrasYipQW2+qT9N72cIxWoEgoj0MKUanYlFYutohb2l5pu3/HhBIw827AuwXSWSX3WFCr1UEdRScN/BVwKsSfTh5lQgI7HRfyNOGsA5vXcCn3LjHrNU8VCOyyG0epz8WM+V0DcZBVTvioC/SFMNz/ofwLe1l3yFQ3qotvLyPHP7H5IV7xrGbZtH+midgFuOG990IJYkPeTsU8PJIsO+MZcNW66HfDA5iDgtoSUJdQj57Ib89yfu7ckcES+WtOz8XlKFAoECu253dBvIGZYJf24C8r2AdM0GoJM/OssUpi5Jh6CJUQuqASDX6t0tg5a1gZrcrb69c3/clBmHB1E4xDhUGezag2P9hFtewxH2Myz/RaSNhLRb6U2cuwNl1yNGJ3IbdeORZqeI0GKwGs4uz7ii67naJ08quAHGRcJ3OTvHCIO9Mni+k4gfBptVeaIS63XkAoHq2cD7CYKDca+/JbLWDawNFZC/8986ulMGHFH0cWD1yDtHkgwnFcHq8lyJ7yKlwuY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
